### ISSUE TITLE
Simplified field expressions

### ISSUE THREAD

**Issue by marcustorres** [garazi/LightningComponentBRK#1]
There are two attributes on Lightning Data Service that allow developers to access record data:

targetRecord - full record representation that is useful for programmatically traversing the record
targetFields - simple, flattened set of field values for ease of use in expressions

May I suggest we change your code to use targetFields vs targetRecord in <forece:recorddata> and thus your expression would change
from: v.broker.fields.Name.value
to: v.broker.Name

**Comment by garazi** [comment]
Done.
